import logging


class ExcludeLogMonitorPollFilter(logging.Filter):
    """Suppresses noisy access logs generated by admin live log polling."""

    def filter(self, record: logging.LogRecord) -> bool:
        message = record.getMessage()
        return '/admin/agile/log-monitor/data/' not in message
