# Generated by Django 5.1.5 on 2026-03-05 08:28

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0023_appsetting'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgileGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Gruppo',
                'verbose_name_plural': 'Gruppi',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterField(
            model_name='systememailtemplate',
            name='key',
            field=models.CharField(choices=[('CHANGE_REQUEST_SUBMITTED', 'Richiesta variazione inviata'), ('REMINDER_PENDING_SUBMISSION', 'Promemoria invio piano'), ('MANAGER_MONTHLY_SUMMARY', 'Riepilogo mensile referente'), ('PLAN_APPROVED', 'Piano approvato'), ('PLAN_REJECTED', 'Piano rifiutato'), ('CHANGE_APPROVED', 'Variazione approvata'), ('CHANGE_REJECTED', 'Variazione rifiutata')], max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role__in', ['ADMIN', 'SUPERADMIN']), ('is_superuser', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Referente amministrativo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Dipendente'), ('ADMIN', 'Referente Amministrativo'), ('SUPERADMIN', 'Super Admin')], default='EMPLOYEE', max_length=20),
        ),
    ]
