# Generated by Django 5.1.5 on 2026-03-06 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0025_user_onboarding_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role__in', ['ADMIN', 'SUPERADMIN']), ('is_superuser', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Responsabile approvazione'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Dipendente'), ('ADMIN', 'Responsabile approvazione'), ('SUPERADMIN', 'Super Admin')], default='EMPLOYEE', max_length=20),
        ),
    ]
